### ISSUE TITLE
preview description of wisdp.com says "this is a ... using create-react-app"

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#104]
**Is your feature request related to a problem? Please describe.**
Figure out and implement a description to be seen on previews of the site.

**Describe the solution you'd like**
**WIP** - The Wisconsin Decarceration Platform helps people engage with service providers in reentry and efforts to reduce recitvism and mass incarceration which harms communities and states.

**Describe alternatives you've considered**

**Additional context**
https://ibb.co/4FPJ6fL - Current Description Preview on Google Results

**Comment by paul-rinaldi** [comment]
Might be how to add a description:
`"description": "____HERE___",` to the `package.json`

**Comment by wolfadex** [comment]
I'm fairly certain you need to update your manifest.json. Possibly some other files in the public directory as well.

**Comment by zawadzkip** [comment]
https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/blob/bceba0a305a13ac71d77708acdbc2d138f3284bf/web-app/public/index.html#L8-L11

I think this is all that will need to be changed.

**Comment by paul-rinaldi** [comment]
> https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/blob/bceba0a305a13ac71d77708acdbc2d138f3284bf/web-app/public/index.html#L8-L11
> 
> I think this is all that will need to be changed.

Worked! commit - https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/commit/0d969975eb8dd9464a1a87622b4440e0498230f5
Was able to see the preview with that description through sending "wisdp.com" over Instagram. Google will need to crawl again to update it in search. Thank you @zawadzkip! Also, thanks for the suggestion @wolfadex.
