### ISSUE TITLE
Implement Front End of the Home Page

### ISSUE THREAD

**Issue by bart1259** [codeformilwaukee/DECARCERATION-PLATFORM#11]
Landing Page needs to **SHOW** visually and **DESCRIBE** _briefly_:
- The purpose of the project
- What we offer to the public
- What we offer to the service providers (link to Login/Sign Up

Elements this might include
- Appbar with Title
- Photos / Video
- Parallax (eventually)

Components to Frontend:
TODO: Draft UI
TODO: Code UI

UI will be shown to Reentry Council for feedback

**Comment by rs6713** [comment]
Hey, I'd be interested in contributing to this. Briefly mocked up the first part of a homepage, let me know if it's any good/completely wrong direction, and if you want me to continue working on it (consider all text potential substitutes)
![image](https://user-images.githubusercontent.com/17339981/84213367-5bdaed00-aab8-11ea-9db8-cd7d23375989.png)

**Comment by paul-rinaldi** [comment]
> Hey, I'd be interested in contributing to this. Briefly mocked up the first part of a homepage, let me know if it's any good/completely wrong direction, and if you want me to continue working on it (consider all text potential substitutes)
> ![image](https://user-images.githubusercontent.com/17339981/84213367-5bdaed00-aab8-11ea-9db8-cd7d23375989.png) @paul-rinaldi

Hi, @rs6713 thanks for the awesome design. 

This reentry tool is (Wisconsin decarceration platform) is based in Milwaukee and so we're looking to use the background of https://www.mkehometostay.org/'s frontpage (currently getting it from the owner).

The layout is great, and the headings/title!

I'll send an IA in a moment for the top and icons!

**Comment by paul-rinaldi** [comment]
@rs6713 

Here's a 
HOME - REENTRY SERVICES - EVENTS - HELP - (Sign In/Up)

Welcome
Wisconsin Decarceration Platform

Get Involved - Get Help - Get Informed

**Comment by paul-rinaldi** [comment]
Here's the photo https://ibb.co/qCFn7CS
