### ISSUE TITLE
Login Button on Appbar should not be absolute

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#18]
When the window viewport is reduced horizontally, the homepage becomes scrollable. And then the login button on the appbar begins crawling down the page. This is not wanted.

Found by @paul-rinaldi .

TODO: Alter CSS / use Material UI Button correctly.

**Comment by paul-rinaldi** [comment]
Hector may pick this issue up

**Comment by rs6713** [comment]
Hello, I'm interested in contributing to this project, but assigning issues doesn't seem possible?
