### ISSUE TITLE
Overall project plan

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/DECARCERATION-PLATFORM#22]
We have MU, UWM, Marquette all willing to participate along with Render and Ekmor to help deliver services to get this project to market. @romkedehaan will be working on the overall plan to pitch for funding and get the orgs to create MOUs to solidify how they will work together.

Draft document will be completed 2nd week of Jan.

**Comment by romkedehaan** [comment]
Let's make sure we define roles with the team.

**Comment by paul-rinaldi** [comment]
OOD and no longer our job
