### ISSUE TITLE
Refine Roadmap

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/DECARCERATION-PLATFORM#23]
We need to create a strong roadmap for the platform that's clear to understand and explain to potential volunteers and stakeholders.

**Subtasks**
* Select how we'll show the roadmap - there are 3 projects of WDP but this site is just the reentry one so github milestones and project views suffice?
* Update each week

Basics: https://docs.google.com/document/d/1_yIYFfVlitTIoirTfl1YvqljbmEDpA7xBaQLgvrTBVo/edit

**Comment by paul-rinaldi** [comment]
Changing to -> Refine current roadmap
Basics: https://docs.google.com/document/d/1_yIYFfVlitTIoirTfl1YvqljbmEDpA7xBaQLgvrTBVo/edit

**Comment by Aycrazy** [comment]
Consider adding a description and a little read me here: digitalpublicworks.org

**Comment by paul-rinaldi** [comment]
Site is unreachable.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Aycrazy** [comment]
whoops try now

**Comment by paul-rinaldi** [comment]
Will come back to later if needed, will talk to other opensource founders about its necessity - currently the roadmap exists in milestones on the readme.
