### ISSUE TITLE
Organization Calendar

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/DECARCERATION-PLATFORM#3]
Organize different events and meetings between organizations all on one online calendar. All organizations can post events with a brief description of what will happen.

**Comment by romkedehaan** [comment]
Wireframe: https://app.moqups.com/nJTJBSUsku/view/page/aa9df7b72

**Comment by paul-rinaldi** [comment]
https://blog.flowandform.agency/create-a-custom-calendar-in-react-3df1bfd0b728?gi=9109b0c096b8 <-- NPM module @flurmbo

**Comment by flurmbo** [comment]
@paul-rinaldi https://github.com/intljusticemission/react-big-calendar

**Comment by paul-rinaldi** [comment]
^ with moment.js!

**Comment by paul-rinaldi** [comment]
UI like this https://devwi.com/calendar

**Comment by paul-rinaldi** [comment]
Closed as of 7/7/2020 by multiple PR's (this is a story type of issue so there was no PR linked)
