### ISSUE TITLE
Add the option to set an event to repeat (daily, weekly, monthly, yearly) in the create event modal

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#37]
As a service provider, I would like to set an event to repeat on certain days, weekly, monthly, or yearly on the shared calendar so that I don't have to always make a new event on the wdp website.

Modal:
https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/issues/34

May need to use:
Moment.js
AWS Dynamo DB

**Comment by hdenisenko** [comment]
is aws set up for this to be implemented yet?
