### ISSUE TITLE
Add a link to 211 Wisconsin for basic needs search

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#40]
ref=https://211wisconsin.communityos.org/guided-search - **211 Madison Basic Needs Search**
ref=https://www.mkehometostay.org/ - **Home to Stay**

Add links to the home page to the above websites

**Comment by hdenisenko** [comment]
@paul-rinaldi hi! I'm interested in contributing to this project. I'm trying to follow the instructions to contribute but I can't seem to assign myself to this issue. I forked this code locally and put together a pr - I'm ready have it go through review but I don't want to do that before assigning myself here. Is there something I need to before starting to assign myself to issues?

**Comment by paul-rinaldi** [comment]
There ya go! @hdenisenko , github doesn't let noncollaborators assign themselves to open source repositories from my googling. Therefore, whenever someone comments that they want an issue, I will assign it.
