### ISSUE TITLE
add website location...?

### ISSUE THREAD

**Issue by kylebakerio** [codeformilwaukee/DECARCERATION-PLATFORM#49]
Is this up anywhere? Even as a unreleased dev-only beta or something? Or does it just have to be run locally?

--
Beta deployment is at https://reentry.netlify.app/ but hosting on AWS is still not done

**Comment by paul-rinaldi** [comment]
No, @kylebakerio , it was and might still be someone on an AWS deployed url but it was lost during some handover, I'm in the process of recovering it. 

This is a valid issue.

Our goal for the next two weeks is to test the current features that are complete so deploying is necessary for UX interviews;

**Comment by paul-rinaldi** [comment]
Deploying to Netlify for now. There are still some bugs to work out - working on them now. https://decarcerationplatform.netlify.app/

**Comment by kylebakerio** [comment]
Just see a page saying 
"not found"

**Comment by paul-rinaldi** [comment]
Sorry, changed it to https://reentry.netlify.app/!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
