### ISSUE TITLE
Add google maps Map to ServicesPage

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#54]
Add google maps Map inside the Box on the ServicesPage below the Service name
Add a config file in source control with fake api keys [discussed here](https://stackoverflow.com/questions/1983990/how-to-open-source-an-application-that-uses-api-keys)

[Mockup](https://balsamiq.cloud/s14elzc/ph76r2x)

Guide if needed:
https://itnext.io/google-maps-react-makes-adding-google-maps-api-to-a-react-app-a-breeze-effb7b89e54

**Comment by hdenisenko** [comment]
@paul-rinaldi i can grab this issue!

**Comment by hdenisenko** [comment]
is there currently an api key for the application? i think that can be added in the `secrets` tab in github!

**Comment by paul-rinaldi** [comment]
I'll have time to add one in a few hours from now, I didn't know about the secret tab, I'll do that! Thanks @hdenisenko

**Comment by paul-rinaldi** [comment]
Added the secret, I think I have to make you a contributor to use it but either way the name is GOOGLE_MAPS_API_KEY... @hdenisenko
