### ISSUE TITLE
Add privacy policy and terms and conditions

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#58]
Todo:
* create privacy policy component and terms
* create conditions component
* create ./privacypolicy route
* create ./termsandconditions route
* ask a contributor @paul-rinaldi to use [TermsFeed](https://app.termsfeed.com/wizard/privacy-policy/) and return that information to you (this will be added when sprint 2 starts)
* add links to privacy policy and terms and conditions links to footer component

Wireframe - [in progress](https://balsamiq.cloud/s14elzc/ph76r2x/rBB73)

**Comment by supernova-at** [comment]
Hey @paul-rinaldi I can help out with this one!
