### ISSUE TITLE
Merge homepage into landingpage (make them both the same page)

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#70]
Add links of homepage to footer and remove the home page and replace it with landing page

**Comment by hdenisenko** [comment]
happy to take this! sorry i've been mia recently - but back with more time now!

**Comment by hdenisenko** [comment]
@paul-rinaldi also something i noticed unrelated to this ticket, but don't know how else to get in touch with you 😬 

i noticed some patterns in the alt text for images used across the app that don't follow alt text standards (i only really recently learned what makes good alt text!) Should i create an issue for that? Or is that something that'll take a lower priority for now?

**Comment by paul-rinaldi** [comment]
> @paul-rinaldi also something i noticed unrelated to this ticket, but don't know how else to get in touch with you 😬
> 
> i noticed some patterns in the alt text for images used across the app that don't follow alt text standards (i only really recently learned what makes good alt text!) Should i create an issue for that? Or is that something that'll take a lower priority for now?

Yes, feel free to make an issue for it, feel free to contact me at rinaldip@msoe.edu!
