### ISSUE TITLE
Alt text isn't being used correctly

### ISSUE THREAD

**Issue by hdenisenko** [codeformilwaukee/DECARCERATION-PLATFORM#77]
I noticed some alt text on images describing what the image is rather than conveying the information that the image conveys to someone who can see the image (https://moz.com/learn/seo/alt-text#:~:text=Alt%20text%20is%20a%20tenet,to%20visually%20identify%20an%20image.) ex: alt="People protesting icon"

Nothing is broken right now, but fixing this would improve SEO outcomes and would make the site more accessible!

**Comment by ValeriKozarev** [comment]
Hi! I'm interested in getting involved and figured I can take this issue. Besides the three icons on the home screen, I didn't find any other images that would need changing. For reference I looked through all the directories at web-app/src/components, let me know if I should be looking elsewhere. Thanks!

**Comment by paul-rinaldi** [comment]
> Hi! I'm interested in getting involved and figured I can take this issue. Besides the three icons on the home screen, I didn't find any other images that would need changing. For reference I looked through all the directories at web-app/src/components, let me know if I should be looking elsewhere. Thanks!

That's correct! Though, the hamburger button on mobile (on the homescreen as well) might count as an icon... needing an alt tag. @hdenisenko , does that sound right ^

**Comment by hdenisenko** [comment]
i'm not seeing hamburger bar in the codebase? is it an icon defined in a component or is it a stand-alone component?
