### ISSUE TITLE
Replace current React webpage Favicon with Wisconsin Decarceration Platform temporary logo

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#86]
**Is your feature request related to a problem? Please describe.**
Favicon should be representative of WDP

**Describe the solution you'd like**
When the webpage opens, the favicon should be the WDP temporary logo

here is the WDP temporary logo: https://drive.google.com/file/d/1vbsmqitRV0xd4bBzcQMOTCCXylaYpSbf/view?usp=sharing

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by paul-rinaldi** [comment]
![Screenshot from 2020-09-09 11-48-40](https://user-images.githubusercontent.com/9328123/92628435-6d3bbd00-f292-11ea-82cc-555590e771be.png)
This is the favicon

**Comment by rohanrk** [comment]
I'd like to pick this up!
