### ISSUE TITLE
Map should not start in San Francisco

### ISSUE THREAD

**Issue by paul-rinaldi** [codeformilwaukee/DECARCERATION-PLATFORM#99]
**Describe the bug**
Map on services page starts in San Francisco until a location is clicked

**To Reproduce**
1. Go to Services Page
4. See bug

**Expected behavior**
When the services page loads, the map should look over WI or MKE County

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Use google-maps-react docs and center map on MKE (lat, lng) 43.0389° N, 87.9065° W

**Comment by finnegan28** [comment]
https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/blob/4ad93d48eb1dbecfecc25688e6810964ed1a0be3/web-app/src/components/ServicesPage/index.js#L174

Try this

```

initialCenter={{
 lat:  43.0389,
 lng: -87.9065
 }}
```

**Comment by paul-rinaldi** [comment]
Worked @finnegan28 , much appreciated :D
